version: '3.3'


services:
  postgres:
    image : postgres:11 
    expose:
      - "5432"
    container_name : postgres
    environment:  
      POSTGRES_DB : testgitdata
      POSTGRES_USER : testuser
      POSTGRES_PASSWORD : testpassword
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql  


  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha45
    ports:
    - "8080:8080"
    container_name : hasura
    depends_on:
      - postgres
    links:
     - postgres  
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://testuser:testpassword@postgres:5432/testgitdata
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" 

        
  python:
    build: .
    container_name : python



